// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ozoncp/ocp-resume-api/internal/flusher (interfaces: Flusher)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	achievement "github.com/ozoncp/ocp-resume-api/internal/achievement"
	resume "github.com/ozoncp/ocp-resume-api/internal/resume"
)

// MockFlusher is a mock of Flusher interface.
type MockFlusher struct {
	ctrl     *gomock.Controller
	recorder *MockFlusherMockRecorder
}

// MockFlusherMockRecorder is the mock recorder for MockFlusher.
type MockFlusherMockRecorder struct {
	mock *MockFlusher
}

// NewMockFlusher creates a new mock instance.
func NewMockFlusher(ctrl *gomock.Controller) *MockFlusher {
	mock := &MockFlusher{ctrl: ctrl}
	mock.recorder = &MockFlusherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlusher) EXPECT() *MockFlusherMockRecorder {
	return m.recorder
}

// FlushAchievements mocks base method.
func (m *MockFlusher) FlushAchievements(arg0 context.Context, arg1 []achievement.Achievement) ([]achievement.Achievement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FlushAchievements", arg0, arg1)
	ret0, _ := ret[0].([]achievement.Achievement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FlushAchievements indicates an expected call of FlushAchievements.
func (mr *MockFlusherMockRecorder) FlushAchievements(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FlushAchievements", reflect.TypeOf((*MockFlusher)(nil).FlushAchievements), arg0, arg1)
}

// FlushResumes mocks base method.
func (m *MockFlusher) FlushResumes(arg0 context.Context, arg1 []resume.Resume) ([]resume.Resume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FlushResumes", arg0, arg1)
	ret0, _ := ret[0].([]resume.Resume)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FlushResumes indicates an expected call of FlushResumes.
func (mr *MockFlusherMockRecorder) FlushResumes(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FlushResumes", reflect.TypeOf((*MockFlusher)(nil).FlushResumes), arg0, arg1)
}
