// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ozoncp/ocp-resume-api/internal/repo (interfaces: Repo)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	achievement "github.com/ozoncp/ocp-resume-api/internal/achievement"
	resume "github.com/ozoncp/ocp-resume-api/internal/resume"
)

// MockRepo is a mock of Repo interface.
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance.
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// AddAchievements mocks base method.
func (m *MockRepo) AddAchievements(arg0 []achievement.Achievement) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAchievements", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddAchievements indicates an expected call of AddAchievements.
func (mr *MockRepoMockRecorder) AddAchievements(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAchievements", reflect.TypeOf((*MockRepo)(nil).AddAchievements), arg0)
}

// AddResumes mocks base method.
func (m *MockRepo) AddResumes(arg0 []resume.Resume) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddResumes", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddResumes indicates an expected call of AddResumes.
func (mr *MockRepoMockRecorder) AddResumes(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddResumes", reflect.TypeOf((*MockRepo)(nil).AddResumes), arg0)
}
