// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: api/ocp-resume-api/ocp-resume-api.proto

package ocp_resume_api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MultiCreateResumesV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resumes []*Resume `protobuf:"bytes,1,rep,name=resumes,proto3" json:"resumes,omitempty"`
}

func (x *MultiCreateResumesV1Request) Reset() {
	*x = MultiCreateResumesV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_resume_api_ocp_resume_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiCreateResumesV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiCreateResumesV1Request) ProtoMessage() {}

func (x *MultiCreateResumesV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_resume_api_ocp_resume_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiCreateResumesV1Request.ProtoReflect.Descriptor instead.
func (*MultiCreateResumesV1Request) Descriptor() ([]byte, []int) {
	return file_api_ocp_resume_api_ocp_resume_api_proto_rawDescGZIP(), []int{0}
}

func (x *MultiCreateResumesV1Request) GetResumes() []*Resume {
	if x != nil {
		return x.Resumes
	}
	return nil
}

type MultiCreateResumesV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResumeIds []uint64 `protobuf:"varint,1,rep,packed,name=ResumeIds,proto3" json:"ResumeIds,omitempty"`
}

func (x *MultiCreateResumesV1Response) Reset() {
	*x = MultiCreateResumesV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_resume_api_ocp_resume_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiCreateResumesV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiCreateResumesV1Response) ProtoMessage() {}

func (x *MultiCreateResumesV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_resume_api_ocp_resume_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiCreateResumesV1Response.ProtoReflect.Descriptor instead.
func (*MultiCreateResumesV1Response) Descriptor() ([]byte, []int) {
	return file_api_ocp_resume_api_ocp_resume_api_proto_rawDescGZIP(), []int{1}
}

func (x *MultiCreateResumesV1Response) GetResumeIds() []uint64 {
	if x != nil {
		return x.ResumeIds
	}
	return nil
}

type UpdateResumeV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResumeId uint64  `protobuf:"varint,1,opt,name=ResumeId,proto3" json:"ResumeId,omitempty"`
	Resume   *Resume `protobuf:"bytes,2,opt,name=resume,proto3" json:"resume,omitempty"`
}

func (x *UpdateResumeV1Request) Reset() {
	*x = UpdateResumeV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_resume_api_ocp_resume_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateResumeV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResumeV1Request) ProtoMessage() {}

func (x *UpdateResumeV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_resume_api_ocp_resume_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResumeV1Request.ProtoReflect.Descriptor instead.
func (*UpdateResumeV1Request) Descriptor() ([]byte, []int) {
	return file_api_ocp_resume_api_ocp_resume_api_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateResumeV1Request) GetResumeId() uint64 {
	if x != nil {
		return x.ResumeId
	}
	return 0
}

func (x *UpdateResumeV1Request) GetResume() *Resume {
	if x != nil {
		return x.Resume
	}
	return nil
}

type UpdateResumeV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Found bool `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
}

func (x *UpdateResumeV1Response) Reset() {
	*x = UpdateResumeV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_resume_api_ocp_resume_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateResumeV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResumeV1Response) ProtoMessage() {}

func (x *UpdateResumeV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_resume_api_ocp_resume_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResumeV1Response.ProtoReflect.Descriptor instead.
func (*UpdateResumeV1Response) Descriptor() ([]byte, []int) {
	return file_api_ocp_resume_api_ocp_resume_api_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateResumeV1Response) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type CreateResumeV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DocumentId uint64 `protobuf:"varint,2,opt,name=DocumentId,proto3" json:"DocumentId,omitempty"`
}

func (x *CreateResumeV1Request) Reset() {
	*x = CreateResumeV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_resume_api_ocp_resume_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateResumeV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResumeV1Request) ProtoMessage() {}

func (x *CreateResumeV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_resume_api_ocp_resume_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResumeV1Request.ProtoReflect.Descriptor instead.
func (*CreateResumeV1Request) Descriptor() ([]byte, []int) {
	return file_api_ocp_resume_api_ocp_resume_api_proto_rawDescGZIP(), []int{4}
}

func (x *CreateResumeV1Request) GetDocumentId() uint64 {
	if x != nil {
		return x.DocumentId
	}
	return 0
}

type CreateResumeV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResumeId uint64 `protobuf:"varint,1,opt,name=ResumeId,proto3" json:"ResumeId,omitempty"`
}

func (x *CreateResumeV1Response) Reset() {
	*x = CreateResumeV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_resume_api_ocp_resume_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateResumeV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResumeV1Response) ProtoMessage() {}

func (x *CreateResumeV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_resume_api_ocp_resume_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResumeV1Response.ProtoReflect.Descriptor instead.
func (*CreateResumeV1Response) Descriptor() ([]byte, []int) {
	return file_api_ocp_resume_api_ocp_resume_api_proto_rawDescGZIP(), []int{5}
}

func (x *CreateResumeV1Response) GetResumeId() uint64 {
	if x != nil {
		return x.ResumeId
	}
	return 0
}

type DescribeResumeV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResumeId uint64 `protobuf:"varint,1,opt,name=ResumeId,proto3" json:"ResumeId,omitempty"`
}

func (x *DescribeResumeV1Request) Reset() {
	*x = DescribeResumeV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_resume_api_ocp_resume_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribeResumeV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResumeV1Request) ProtoMessage() {}

func (x *DescribeResumeV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_resume_api_ocp_resume_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResumeV1Request.ProtoReflect.Descriptor instead.
func (*DescribeResumeV1Request) Descriptor() ([]byte, []int) {
	return file_api_ocp_resume_api_ocp_resume_api_proto_rawDescGZIP(), []int{6}
}

func (x *DescribeResumeV1Request) GetResumeId() uint64 {
	if x != nil {
		return x.ResumeId
	}
	return 0
}

type DescribeResumeV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resume *Resume `protobuf:"bytes,1,opt,name=resume,proto3" json:"resume,omitempty"`
}

func (x *DescribeResumeV1Response) Reset() {
	*x = DescribeResumeV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_resume_api_ocp_resume_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribeResumeV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResumeV1Response) ProtoMessage() {}

func (x *DescribeResumeV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_resume_api_ocp_resume_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResumeV1Response.ProtoReflect.Descriptor instead.
func (*DescribeResumeV1Response) Descriptor() ([]byte, []int) {
	return file_api_ocp_resume_api_ocp_resume_api_proto_rawDescGZIP(), []int{7}
}

func (x *DescribeResumeV1Response) GetResume() *Resume {
	if x != nil {
		return x.Resume
	}
	return nil
}

type ListResumesV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit  uint64 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset uint64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *ListResumesV1Request) Reset() {
	*x = ListResumesV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_resume_api_ocp_resume_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListResumesV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResumesV1Request) ProtoMessage() {}

func (x *ListResumesV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_resume_api_ocp_resume_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResumesV1Request.ProtoReflect.Descriptor instead.
func (*ListResumesV1Request) Descriptor() ([]byte, []int) {
	return file_api_ocp_resume_api_ocp_resume_api_proto_rawDescGZIP(), []int{8}
}

func (x *ListResumesV1Request) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListResumesV1Request) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListResumesV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resumes []*Resume `protobuf:"bytes,1,rep,name=resumes,proto3" json:"resumes,omitempty"`
}

func (x *ListResumesV1Response) Reset() {
	*x = ListResumesV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_resume_api_ocp_resume_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListResumesV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResumesV1Response) ProtoMessage() {}

func (x *ListResumesV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_resume_api_ocp_resume_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResumesV1Response.ProtoReflect.Descriptor instead.
func (*ListResumesV1Response) Descriptor() ([]byte, []int) {
	return file_api_ocp_resume_api_ocp_resume_api_proto_rawDescGZIP(), []int{9}
}

func (x *ListResumesV1Response) GetResumes() []*Resume {
	if x != nil {
		return x.Resumes
	}
	return nil
}

type RemoveResumeV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResumeId uint64 `protobuf:"varint,1,opt,name=ResumeId,proto3" json:"ResumeId,omitempty"`
}

func (x *RemoveResumeV1Request) Reset() {
	*x = RemoveResumeV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_resume_api_ocp_resume_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveResumeV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveResumeV1Request) ProtoMessage() {}

func (x *RemoveResumeV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_resume_api_ocp_resume_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveResumeV1Request.ProtoReflect.Descriptor instead.
func (*RemoveResumeV1Request) Descriptor() ([]byte, []int) {
	return file_api_ocp_resume_api_ocp_resume_api_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveResumeV1Request) GetResumeId() uint64 {
	if x != nil {
		return x.ResumeId
	}
	return 0
}

type RemoveResumeV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Found bool `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
}

func (x *RemoveResumeV1Response) Reset() {
	*x = RemoveResumeV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_resume_api_ocp_resume_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveResumeV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveResumeV1Response) ProtoMessage() {}

func (x *RemoveResumeV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_resume_api_ocp_resume_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveResumeV1Response.ProtoReflect.Descriptor instead.
func (*RemoveResumeV1Response) Descriptor() ([]byte, []int) {
	return file_api_ocp_resume_api_ocp_resume_api_proto_rawDescGZIP(), []int{11}
}

func (x *RemoveResumeV1Response) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type Resume struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         uint64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	DocumentId uint64 `protobuf:"varint,2,opt,name=DocumentId,proto3" json:"DocumentId,omitempty"`
}

func (x *Resume) Reset() {
	*x = Resume{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_resume_api_ocp_resume_api_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resume) ProtoMessage() {}

func (x *Resume) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_resume_api_ocp_resume_api_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resume.ProtoReflect.Descriptor instead.
func (*Resume) Descriptor() ([]byte, []int) {
	return file_api_ocp_resume_api_ocp_resume_api_proto_rawDescGZIP(), []int{12}
}

func (x *Resume) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Resume) GetDocumentId() uint64 {
	if x != nil {
		return x.DocumentId
	}
	return 0
}

var File_api_ocp_resume_api_ocp_resume_api_proto protoreflect.FileDescriptor

var file_api_ocp_resume_api_ocp_resume_api_proto_rawDesc = []byte{
	0x0a, 0x27, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65,
	0x2d, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x2d,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x6f, 0x63, 0x70, 0x2e, 0x72,
	0x65, 0x73, 0x75, 0x6d, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4f, 0x0a, 0x1b, 0x4d, 0x75, 0x6c, 0x74, 0x69,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x73, 0x56, 0x31, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x72, 0x65,
	0x73, 0x75, 0x6d, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x52,
	0x07, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x73, 0x22, 0x3c, 0x0a, 0x1c, 0x4d, 0x75, 0x6c, 0x74,
	0x69, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x73, 0x56, 0x31,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x73, 0x75,
	0x6d, 0x65, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x09, 0x52, 0x65, 0x73,
	0x75, 0x6d, 0x65, 0x49, 0x64, 0x73, 0x22, 0x63, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x08, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6f, 0x63,
	0x70, 0x2e, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73,
	0x75, 0x6d, 0x65, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x22, 0x2e, 0x0a, 0x16, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x56, 0x31, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x22, 0x37, 0x0a, 0x15, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x56, 0x31, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x22, 0x34, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x75, 0x6d, 0x65, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x08, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x49, 0x64, 0x22, 0x35, 0x0a, 0x17, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x56, 0x31, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x49,
	0x64, 0x22, 0x4a, 0x0a, 0x18, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x73,
	0x75, 0x6d, 0x65, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x6f, 0x63, 0x70, 0x2e, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52,
	0x65, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x22, 0x44, 0x0a,
	0x14, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x73, 0x56, 0x31, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f,
	0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x22, 0x49, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6d,
	0x65, 0x73, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x07,
	0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x6f, 0x63, 0x70, 0x2e, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52,
	0x65, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x73, 0x22, 0x33,
	0x0a, 0x15, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x56, 0x31,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x75, 0x6d,
	0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x52, 0x65, 0x73, 0x75, 0x6d,
	0x65, 0x49, 0x64, 0x22, 0x2e, 0x0a, 0x16, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73,
	0x75, 0x6d, 0x65, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6f,
	0x75, 0x6e, 0x64, 0x22, 0x38, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1e, 0x0a,
	0x0a, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0a, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x32, 0x99, 0x06,
	0x0a, 0x0c, 0x4f, 0x63, 0x70, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x41, 0x70, 0x69, 0x12, 0x77,
	0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x56, 0x31,
	0x12, 0x25, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x56, 0x31,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x72, 0x65,
	0x73, 0x75, 0x6d, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x75, 0x6d, 0x65, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x16, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x10, 0x22, 0x0b, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x73,
	0x75, 0x6d, 0x65, 0x73, 0x3a, 0x01, 0x2a, 0x12, 0x8f, 0x01, 0x0a, 0x14, 0x4d, 0x75, 0x6c, 0x74,
	0x69, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x73, 0x56, 0x31,
	0x12, 0x2b, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x75, 0x6d, 0x65, 0x73, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e,
	0x6f, 0x63, 0x70, 0x2e, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d,
	0x75, 0x6c, 0x74, 0x69, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65,
	0x73, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1c, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x16, 0x22, 0x11, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x73,
	0x5f, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x3a, 0x01, 0x2a, 0x12, 0x82, 0x01, 0x0a, 0x0e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x56, 0x31, 0x12, 0x25, 0x2e, 0x6f,
	0x63, 0x70, 0x2e, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d,
	0x65, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x21, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x1b, 0x1a, 0x16, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x73,
	0x2f, 0x7b, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x49, 0x64, 0x7d, 0x3a, 0x01, 0x2a, 0x12, 0x85,
	0x01, 0x0a, 0x10, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d,
	0x65, 0x56, 0x31, 0x12, 0x27, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x73,
	0x75, 0x6d, 0x65, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x6f,
	0x63, 0x70, 0x2e, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x56, 0x31, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x18, 0x12, 0x16,
	0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x73, 0x2f, 0x7b, 0x52, 0x65, 0x73,
	0x75, 0x6d, 0x65, 0x49, 0x64, 0x7d, 0x12, 0x70, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x75, 0x6d, 0x65, 0x56, 0x31, 0x12, 0x24, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x72, 0x65, 0x73,
	0x75, 0x6d, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x75,
	0x6d, 0x65, 0x73, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x6f,
	0x63, 0x70, 0x2e, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x73, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x13, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0d, 0x12, 0x0b, 0x2f, 0x76, 0x31,
	0x2f, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x73, 0x12, 0x7f, 0x0a, 0x0e, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x56, 0x31, 0x12, 0x25, 0x2e, 0x6f, 0x63, 0x70,
	0x2e, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x26, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x56,
	0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1e, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x18, 0x2a, 0x16, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x73, 0x2f, 0x7b,
	0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x49, 0x64, 0x7d, 0x42, 0x44, 0x5a, 0x42, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x7a, 0x6f, 0x6e, 0x63, 0x70, 0x2f, 0x6f,
	0x63, 0x70, 0x2d, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x2d, 0x61, 0x70, 0x69,
	0x3b, 0x6f, 0x63, 0x70, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_ocp_resume_api_ocp_resume_api_proto_rawDescOnce sync.Once
	file_api_ocp_resume_api_ocp_resume_api_proto_rawDescData = file_api_ocp_resume_api_ocp_resume_api_proto_rawDesc
)

func file_api_ocp_resume_api_ocp_resume_api_proto_rawDescGZIP() []byte {
	file_api_ocp_resume_api_ocp_resume_api_proto_rawDescOnce.Do(func() {
		file_api_ocp_resume_api_ocp_resume_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_ocp_resume_api_ocp_resume_api_proto_rawDescData)
	})
	return file_api_ocp_resume_api_ocp_resume_api_proto_rawDescData
}

var file_api_ocp_resume_api_ocp_resume_api_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_ocp_resume_api_ocp_resume_api_proto_goTypes = []interface{}{
	(*MultiCreateResumesV1Request)(nil),  // 0: ocp.resume.api.MultiCreateResumesV1Request
	(*MultiCreateResumesV1Response)(nil), // 1: ocp.resume.api.MultiCreateResumesV1Response
	(*UpdateResumeV1Request)(nil),        // 2: ocp.resume.api.UpdateResumeV1Request
	(*UpdateResumeV1Response)(nil),       // 3: ocp.resume.api.UpdateResumeV1Response
	(*CreateResumeV1Request)(nil),        // 4: ocp.resume.api.CreateResumeV1Request
	(*CreateResumeV1Response)(nil),       // 5: ocp.resume.api.CreateResumeV1Response
	(*DescribeResumeV1Request)(nil),      // 6: ocp.resume.api.DescribeResumeV1Request
	(*DescribeResumeV1Response)(nil),     // 7: ocp.resume.api.DescribeResumeV1Response
	(*ListResumesV1Request)(nil),         // 8: ocp.resume.api.ListResumesV1Request
	(*ListResumesV1Response)(nil),        // 9: ocp.resume.api.ListResumesV1Response
	(*RemoveResumeV1Request)(nil),        // 10: ocp.resume.api.RemoveResumeV1Request
	(*RemoveResumeV1Response)(nil),       // 11: ocp.resume.api.RemoveResumeV1Response
	(*Resume)(nil),                       // 12: ocp.resume.api.Resume
}
var file_api_ocp_resume_api_ocp_resume_api_proto_depIdxs = []int32{
	12, // 0: ocp.resume.api.MultiCreateResumesV1Request.resumes:type_name -> ocp.resume.api.Resume
	12, // 1: ocp.resume.api.UpdateResumeV1Request.resume:type_name -> ocp.resume.api.Resume
	12, // 2: ocp.resume.api.DescribeResumeV1Response.resume:type_name -> ocp.resume.api.Resume
	12, // 3: ocp.resume.api.ListResumesV1Response.resumes:type_name -> ocp.resume.api.Resume
	4,  // 4: ocp.resume.api.OcpResumeApi.CreateResumeV1:input_type -> ocp.resume.api.CreateResumeV1Request
	0,  // 5: ocp.resume.api.OcpResumeApi.MultiCreateResumesV1:input_type -> ocp.resume.api.MultiCreateResumesV1Request
	2,  // 6: ocp.resume.api.OcpResumeApi.UpdateResumeV1:input_type -> ocp.resume.api.UpdateResumeV1Request
	6,  // 7: ocp.resume.api.OcpResumeApi.DescribeResumeV1:input_type -> ocp.resume.api.DescribeResumeV1Request
	8,  // 8: ocp.resume.api.OcpResumeApi.ListResumeV1:input_type -> ocp.resume.api.ListResumesV1Request
	10, // 9: ocp.resume.api.OcpResumeApi.RemoveResumeV1:input_type -> ocp.resume.api.RemoveResumeV1Request
	5,  // 10: ocp.resume.api.OcpResumeApi.CreateResumeV1:output_type -> ocp.resume.api.CreateResumeV1Response
	1,  // 11: ocp.resume.api.OcpResumeApi.MultiCreateResumesV1:output_type -> ocp.resume.api.MultiCreateResumesV1Response
	3,  // 12: ocp.resume.api.OcpResumeApi.UpdateResumeV1:output_type -> ocp.resume.api.UpdateResumeV1Response
	7,  // 13: ocp.resume.api.OcpResumeApi.DescribeResumeV1:output_type -> ocp.resume.api.DescribeResumeV1Response
	9,  // 14: ocp.resume.api.OcpResumeApi.ListResumeV1:output_type -> ocp.resume.api.ListResumesV1Response
	11, // 15: ocp.resume.api.OcpResumeApi.RemoveResumeV1:output_type -> ocp.resume.api.RemoveResumeV1Response
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_ocp_resume_api_ocp_resume_api_proto_init() }
func file_api_ocp_resume_api_ocp_resume_api_proto_init() {
	if File_api_ocp_resume_api_ocp_resume_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_ocp_resume_api_ocp_resume_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiCreateResumesV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_resume_api_ocp_resume_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiCreateResumesV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_resume_api_ocp_resume_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateResumeV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_resume_api_ocp_resume_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateResumeV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_resume_api_ocp_resume_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateResumeV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_resume_api_ocp_resume_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateResumeV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_resume_api_ocp_resume_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribeResumeV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_resume_api_ocp_resume_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribeResumeV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_resume_api_ocp_resume_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListResumesV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_resume_api_ocp_resume_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListResumesV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_resume_api_ocp_resume_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveResumeV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_resume_api_ocp_resume_api_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveResumeV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_resume_api_ocp_resume_api_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Resume); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_ocp_resume_api_ocp_resume_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ocp_resume_api_ocp_resume_api_proto_goTypes,
		DependencyIndexes: file_api_ocp_resume_api_ocp_resume_api_proto_depIdxs,
		MessageInfos:      file_api_ocp_resume_api_ocp_resume_api_proto_msgTypes,
	}.Build()
	File_api_ocp_resume_api_ocp_resume_api_proto = out.File
	file_api_ocp_resume_api_ocp_resume_api_proto_rawDesc = nil
	file_api_ocp_resume_api_ocp_resume_api_proto_goTypes = nil
	file_api_ocp_resume_api_ocp_resume_api_proto_depIdxs = nil
}
